require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - tmp/**/*
    - config.ru
  TargetRubyVersion: 3.3.3

Style/ClassAndModuleChildren:
  Enabled: false

